const dbContents = {
    products: [
        {
            name: "Baby Florida Ghost (Philodendron)",
            description:
                "This is a ghost you want in your house! The Philodendron Florida Ghost is a very rare plant with amazing abilities. Young leaves turn white and slowly fade to green. All in all a great plant that will steal the show in your urban jungle!",
            image: "bby_florida_ghost.png",
            typeId: 1,
            stock: 18,
            price: 32.45,
            trending: false,
            slug: "baby-florida-ghost",
        },
        {
            name: "Baby Frydek (Alocasia, Elephant Ears)",
            description:
                "The Alocasia Frydek is also known as the Green Velvet Alocasia because of its velvety leaves. You can recognise her by her arrow-shaped foliage with beautiful bright white veins.",
            image: "bby_frydek.png",
            typeId: 1,
            stock: 20,
            price: 8.75,
            trending: false,
            slug: "baby-frydek",
        },
        {
            name: "Baby Jacklyn (Alocasia, Elephant Ears)",
            description:
                "This Baby Alocasia is one with extraordinary leaf shape! This is the Alocasia Jacklyn and she is really something special. These amazing leaves are covered in dark green nerves, a real artwork from leaves to roots. This plant is not known by many plant parents yet, since she was only discovered pretty recently. Don't hesitate to add this rare beauty to your ever growing home!",
            image: "bby_jacklyn.png",
            typeId: 1,
            stock: 3,
            price: 14.95,
            trending: true,
            slug: "baby-jacklyn",
        },
        {
            name: "Baby Melanochrysum (Philodendron)",
            description:
                "Have you ever seen a cuter Philodendron Melanochrysum? This stunning rare plant is known for her long leaves with velvet look to them. New leaves start out with a fleshy pink tone that will fade down into a very dark green colour. She can have some gold accents on her leaves as well, which contrasts her dark base beautifully! She is a climber and would love to have something to grow onto.",
            image: "bby_melanochrysum.png",
            typeId: 1,
            stock: 15,
            price: 14.45,
            trending: true,
            slug: "baby-melanochrysum",
        },
        {
            name: "Baby Obliqua (Monstera)",
            description:
                "The Obliqua is already the smallest species of the Monstera family. The Monstera Obliqua stands out with her extremely fenestrated leaves and frayed leaf edges. This unicorn plant is the one for rare plant collectors. No matter how big your collection will grow, this plant will take her moment of shine!",
            image: "bby_obliqua.png",
            typeId: 1,
            stock: 3,
            price: 29.45,
            trending: true,
            slug: "baby-obliqua",
        },
        {
            name: "Baby Pink Princess (Philodendron)",
            description:
                "The Philodendron Pink Princess has beautiful dark green leaves, that are decorated with an explosion of pink colour. Even the undersides of her leaves have an amazing red/coppery hue. She really is a living work of art.",
            image: "bby_pink_princess.png",
            typeId: 1,
            stock: 7,
            price: 12.45,
            trending: true,
            slug: "baby_pink_princess",
        },
        {
            name: "Baby Rowleyanus (Senecio, String of pearls)",
            description:
                "The Senecio Rowleyanus, commonly known as String of Pearls, is an easy-care hanging plant. She owns her nickname to the characteristic small green balls on the plant that are similar to pearls. The rowleyanus is a woman of many names, even referred to as ‘Pearl Plant’ and ‘String of Beads’. She is a beautiful and fun plant that will add a little quirkiness to any home!",
            image: "bby_rowleyanus.png",
            typeId: 1,
            stock: 5,
            price: 6.95,
            trending: true,
            slug: "baby-rowleyanus",
        },
        {
            name: "Baby Thai Constellation (Monstera)",
            description:
                "Here is the most beloved and rare Thai Constellation. She earns her name on her variegation that looks like a constellation. In contrast to most variegated plants, the Thai's variegation is stable, yay! This is because she was especially produced for this, which also means that you will not be able to find this cutie anywhere in nature.",
            image: "bby_thai_constellation.png",
            typeId: 1,
            stock: 12,
            price: 44.95,
            trending: true,
            slug: "baby-thai-constellation",
        },
        {
            name: "Baby Warocqueanum (Anthurium, Flamingo flowers)",
            description:
                "This small baby will grow into a magnificent plant with huge leaves! This is the Anthurium Warocqueanum and she is loved for her rich and dark foliage. With this baby you have the chance to admire her growth in every life stage, which is pretty fascinating.",
            image: "bby_warocqueanum.png",
            typeId: 1,
            stock: 20,
            price: 32.45,
            trending: true,
            slug: "baby-warocqueanum",
        },
        {
            name: "Baby Zebrina (Alocasia, Elephant Ears)",
            description:
                "The baby Alocasia Zebrina is the princess of the plant savannah. With her beautiful zebra-striped stems she is a feast for the eyes. In nature her leaves grow so big that Alocasias are often called the ‘elephant's ear' plant. For many animals in the South East Asian rainforest, the leaves of the Alocasia Zebrina, which can sometimes grow up to 100 centimetres in size, offer a safe hiding place.",
            image: "bby_zebrina.png",
            typeId: 1,
            stock: 11,
            price: 7.45,
            trending: true,
            slug: "Baby-Zebrina",
        },
        {
            name: "Aquatica (Pachira, Money tree)",
            description:
                "The braided Pachira Aquatica is a beautiful plant with a braided trunk. Despite her Latin American roots, the Pachira Aquatica is best known in Asia. Her leaves are five-pointed and therefore symbolic in feng shui. She is a real asset as a large houseplant, as she grows fast! In nature, it can even grow up to 25 metres tall! You would then almost say she is a tree rather than a houseplant.",
            image: "aquatica.png",
            typeId: 1,
            stock: 20,
            price: 82.45,
            trending: true,
            slug: "aquatica",
        },
        {
            name: "Charlotte (Schefflera, Umbrella tree)",
            description:
                "The Schefflera Charlotte is often called an umbrella tree, and her variegated leaves make her an eye-catching addition to any plant collection. The characteristic parasol-shaped spreads of leaves are elongated and might remind you of a hand. She will quickly turn out to be one of your favs, because she can make herself at home anywhere.",
            image: "charlotte.png",
            typeId: 1,
            stock: 2,
            price: 12.95,
            trending: true,
            slug: "charlotte",
        },
        {
            name: "Coconut (Palm, Cocos nucifera)",
            description:
                "The Cocos Nucifera, better known as “Coconut Palm”, is a green houseplant that is part of, you guessed it, the palm family! This tropical beauty is extra special since the plant grows directly from a coconut. Despite not having many leaves, the Coconut Palm still scores well at filtering the air. This is because palms are naturally very adept air filterers.",
            image: "coconut.png",
            typeId: 1,
            stock: 6,
            price: 22.95,
            trending: true,
            slug: "coconut",
        },
        {
            name: "Deliciosa Variegated (Monstera)",
            description:
                "The Monstera ''Borsigiana'' Deliciosa Variegated is a real show stopper! Her leaves are big, beautiful and heart-shaped, just like a regular Monstera Deliciosa. The thing that makes her special is the deviating colour on her leaves.",
            image: "deliciosa_variegated.png",
            typeId: 1,
            stock: 10,
            price: 104.95,
            trending: true,
            slug: "deliciosa-variegated",
        },
        {
            name: "Dragon Jade (Dischidia, Dischidia Nummularifolia)",
            description:
                "This beauty is known for its stacked foliage which looks like it came right out of a fairytale! This couldn't be any other plant than the Dischidia Dragon Jade! Its luscious, cascading leaves create a dreamy vibe, making every day feel like a stroll through a magical woodland.",
            image: "dragon_jade.png",
            typeId: 1,
            stock: 3,
            price: 13.95,
            trending: true,
            slug: "dragon-jade",
        },
        {
            name: "Gageana (Alocasia, Elephant Ears)",
            description:
                "The Alocasia Gageana is like lots of Alocasias known as the Elephant Ear plant. She owes that name to her large, deep green, ribbed leaves which just look alike. This beauty likes to occupy a lot of space as she is used to in her natural environment. This way she is able to grow great heights and really show her splendour within your room.",
            image: "gageana.png",
            typeId: 1,
            stock: 3,
            price: 31.45,
            trending: true,
            slug: "gageana",
        },
        {
            name: "Lutescens (Dypsis, Golden Cane Palm)",
            description:
                "This Dypsis Lutescens is everything you are longing for! This plant consists of multiple ‘palms' inside one pot, together they form this massive plant! She will definitely brighten up your house with her bright green pinnate leaves. You might have heard about this plant under the name ‘Butterfly Palm', which we think is a very fitting nickname for this stunner!",
            image: "lutescens.png",
            typeId: 1,
            stock: 3,
            price: 113.45,
            trending: true,
            slug: "lutescens",
        },
        {
            name: "Lyrata Branched (Ficus, Fiddle Leaf Fig)",
            description:
                "The Ficus Lyrata, also known as the fig-leaf plant or violet leaf plant, is a huge feast for the eyes and is really one of our favourites. The beautiful large, strong heart-shaped leaves grow proudly upwards and give her a dignified appearance. This giant beauty is extra special as she has multiple branches. This way she easily fills up the room, not only in height but also in width!",
            image: "lyrata_branched.png",
            typeId: 1,
            stock: 5,
            price: 143.45,
            trending: true,
            slug: "lyrata-branched",
        },
        {
            name: "Maculata (Begonia, Polka Dot)",
            description:
                "The Begonia Maculata is also known as the ‘Polka dot' Begonia or ‘Forel' Begonia. Its leaves are olive green and freckled with silvery-white spots on its upper surface. The reverse side is known for its eye-catching red-Bordeaux color. We advise you to place the Begonia Maculata in a spot with plenty of light and warmth. Prevent dehydration by watering the baby plant two times a week.",
            image: "maculata.png",
            typeId: 1,
            stock: 8,
            price: 15.45,
            trending: true,
            slug: "maculata",
        },
        {
            name: "Melanochrysum (Philodendron)",
            description:
                "Philodendron Melanochrysum is striking, referred to as the Black Gold Philodendron because of the beautiful gold accents on her leaves. Her leaves, which start out like a fleshy pink before turning almost black with age, get bigger and bigger as she gets taller! She is a climber so will be happiest when she has something like a mossy stick to climb up.",
            image: "melanochrysum.png",
            typeId: 1,
            stock: 7,
            price: 42.45,
            trending: true,
            slug: "melanochrysum",
        },
        {
            name: "Oppenheimiana (Calathea, Prayer Plant)",
            description:
                "Calathea oppenheimiana, originally from South America. She is known for her striking, dark green leaves with elongated white or yellow patterns, resembling the stripes of a zebra. Besides the beautiful patterns, the leaves of the Oppenheimiana also have a beautiful deep red colour on the back of the leaves. She will also 'close' her leaves at night to open again in the morning.",
            image: "oppenheimiana.png",
            typeId: 1,
            stock: 3,
            price: 89.95,
            trending: true,
            slug: "oppenheimiana",
        },
        {
            name: "Paradoxa Minor (Rhipsalis, Fishbone cactus) ",
            description:
                "The Rhipsalis Paradoxa Minor has a very distinctive look. She has long stems that can be thick, thin, straight or slightly curled. These cool stems hang from her pot, giving her a very noteworthy look! So if you are looking for a cool houseplant with an uncommon appearance, you have found your match!",
            image: "paradoxa_minor.png",
            typeId: 1,
            stock: 3,
            price: 70.95,
            trending: true,
            slug: "paradoxa-minor",
        },
        {
            name: "Pink Dragon (Alocasia, Elephant Ear)",
            description:
                "The Alocasia Pink Dragon is a special plant. This ultimate eye-catcher stands out with its pink stalks and metallic silver leaves. Once you see the Alocasia Pink Dragon you'll understand why it demands a special place in your living room!",
            image: "pink_dragon.png",
            typeId: 1,
            stock: 3,
            price: 17.45,
            trending: true,
            slug: "pink-dragon",
        },
        {
            name: "Pinnatum Variegata (Epipremnum, Pothos) ",
            description:
                "Ready to be stunned by magnificent marble variegated leaves? Introducing the Epipremnum Pinnatum Variegata! With its vibrant green leaves adorned in captivating marble-like patterns, this gem is an absolute showstopper. No matter how many beauties grace your urban oasis, the Variegata effortlessly steals the spotlight.",
            image: "pinnatum_variegata.png",
            typeId: 1,
            stock: 3,
            price: 112.95,
            trending: true,
            slug: "pinnatum-variegata",
        },
        {
            name: "Ramulosa Red Coral (Rhipsalis)",
            description:
                "The Rhipsalis Ramulosa Red Coral has very special foliage. This will change from green to having a red tint when she receives enough light. This stunning foliage hangs from her pot, making her a perfect candidate for that empty place inside your cabinet!",
            image: "ramulosa_red_coral.png",
            typeId: 1,
            stock: 3,
            price: 28.95,
            trending: true,
            slug: "ramulosa-red-coral",
        },
        {
            name: "Red Secret (Alocasia, Mirror plant)",
            description:
                "A beautiful room plant with large leaves. The Alocasia is also called Elephant's ear. Really an urban jungle plant that you will rarely encounter!",
            image: "red_secret.png",
            typeId: 1,
            stock: 3,
            price: 15.45,
            trending: true,
            slug: "red-secret",
        },
        {
            name: "Regal Shield (Alocasia, Elephant Ear)",
            description:
                "The Alocasia Regal Shields is part of the Arum family and originates from Asia. Don't forget to take a look at the bottom of its leaves as well, these are a gorgeous shade of deep purple!",
            image: "regal_shield.png",
            typeId: 1,
            stock: 3,
            price: 38.45,
            trending: true,
            slug: "regal-shield",
        },
        {
            name: "Stingray (Alocasia, Elephant Ears)",
            description:
                "The Alocasia Stingray originates from the tropics of South East Asia. In the tropics the leaves of the Alocasia Stingray are used as a hideout for animals because they can grow up till 1 meter wide. It was named after the stingray because of the shape of its leaves.",
            image: "stingray.png",
            typeId: 1,
            stock: 3,
            price: 14.45,
            trending: true,
            slug: "stingray",
        },
        {
            name: "Tineke (Ficus, Rubber tree plant)",
            description:
                "The Ficus elastica is also known as the rubber tree. She earned this nickname thanks to the plant sap, that was once used for the production of rubber. Nowadays, this popular plant steals the show in many a living room, where she also provides purified air. NASA even proclaimed her one of the top-10 most air-purifying houseplants in the world!",
            image: "tineke.png",
            typeId: 1,
            stock: 3,
            price: 48.95,
            trending: true,
            slug: "tineke",
        },
        {
            name: "Bird of Paradise (Strelitzia Nicolai)",
            description:
                "The Strelitzia Nicolai comes from South Africa and has beautiful large leaves that transform your house into a real jungle. In the wild the plant grows up to 10 meters high. As this plant grows older she will start splitting her leaves, this is perfectly normal! It's an evolutionary adaptation of the plant for the wind to pass through the leaves.",
            image: "bird_of_paradise.png",
            typeId: 1,
            stock: 11,
            price: 43.95,
            trending: true,
            slug: "bird-of-paradise",
        },
        {
            name: "Elho Vick Pot White",
            description:
                "His soft white colour and basic shape make Vick very easygoing, fitting into any interior and with any large plant, including inner pot. This pot by Elho is made of 100% recycled plastic.",
            image: "elho_vick_pot_white.png",
            typeId: 2,
            stock: 7,
            price: 22.95,
            trending: true,
            slug: "elho-vick-pot-white",
        },
        {
            name: "Elho Miles Round Pot Green",
            description:
                "Miles is a beautiful basic pot with a sleek design. Miles is also very practical, as he has an integrated water reservoir so your plants always have enough water, he is waterproof and made of 100% recycled plastic. Miles is also frost-resistant so he can stand outside.",
            image: "elho_miles_round_pot_green.png",
            typeId: 2,
            stock: 22,
            price: 17.45,
            trending: true,
            slug: "elho-miles-round-pot-green",
        },
        {
            name: "Set of 5 Nursery Planters Ø 12 cm",
            description:
                "Nursery planters are the basis of any good plant care. Because there are holes in the bottom of the inner pot, water is given a chance to drain gradually, which helps against root rot. This fact keeps your plant and its roots happy, which is why we always recommend using a grow pot.",
            image: "set_of_5_nursery_planters_12_cm.png",
            typeId: 2,
            stock: 5,
            price: 5.45,
            trending: true,
            slug: "set-of-5-nursery-planters-12-cm",
        },
        {
            name: "Set of 10 Nursery Planters Ø 15 cm",
            description:
                "Nursery planters are the basis of any good plant care. Because there are holes in the bottom of the inner pot, water is given a chance to drain gradually, which helps against root rot. ",
            image: "set_of_10_nursery_planters_15_cm.png",
            typeId: 2,
            stock: 11,
            price: 9.45,
            trending: true,
            slug: "set-of-10-nursery-planters-15-cm",
        },
        {
            name: "Hubert Pot Terra Ø 13.5 cm",
            description:
                "Our Hubert is sophisticated and classy, due to his rounded design. What makes him even more special is that he is made from an earthy material. He is made from concrete in a taupe colour. This material makes Hubert strong and will last for ages.",
            image: "hubert_pot_terra.png",
            typeId: 2,
            stock: 10,
            price: 28.95,
            trending: true,
            slug: "hubert.pot-terra",
        },
        {
            name: "Baby Lisa Pot Green Ø 7 cm",
            description:
                "Our Limited edition summer line will help you to add some colour and summer vibes into your home.",
            image: "baby_lisa_pot_green.png",
            typeId: 2,
            stock: 8,
            price: 5.95,
            trending: true,
            slug: "baby-lisa-pot-green",
        },
        {
            name: "Lisa Pot Dusty Petrol Ø 15 cm",
            description:
                "New season, new look for Lisa! She shines in some new trendy colors like dusty terracotta, ochre, and petrol, giving your interior a touch of vintage.",
            image: "lisa_pot_dusty_petrol.png",
            typeId: 2,
            stock: 15,
            price: 12.45,
            trending: true,
            slug: "lisa-pot-dusty-petrol",
        },
        {
            name: "Baby Otis Pot Ocher Ø 9 cm",
            description:
                "Meet Otis, your plant's new fashion statement! With a groovy shape and the glossy finish and textured design, it's the perfect space for your baby plants to shine.",
            image: "baby_otis_pot_ocher.png",
            typeId: 2,
            stock: 6,
            price: 11.95,
            trending: true,
            slug: "baby-otis-pot-ocher",
        },
        {
            name: "Splanky Pot Green Blue Ø 22.5 cm",
            description:
                "With its splashing glaze and unique design, Splanky brings those retro vibes to your urban jungle.",
            image: "splanky_pot_green_blue.png",
            typeId: 2,
            stock: 15,
            price: 43.95,
            trending: true,
            slug: "splanky-pot-green-blue",
        },
        {
            name: "Sanny Pot Blue Ø 18 cm",
            description:
                "This pot is a stunning brown color with white speckles, adding a touch of uniqueness to your space.",
            image: "sanny_pot_blue.png",
            typeId: 2,
            stock: 5,
            price: 11.37,
            trending: true,
            slug: "sanny-pot-blue",
        },
        {
            name: "Ava Pot Cream Ø 6.5 cm",
            description:
                "The Ava potting line is made of ceramics and based on natural earth tones. These earth tones provide warmth and a relaxing atmosphere.",
            image: "ava_pot_cream.png",
            typeId: 2,
            stock: 11,
            price: 6.95,
            trending: true,
            slug: "ava-pot-cream",
        },
        {
            name: "Amy Basket Jute Ø 21 cm",
            description:
                "The Amy basket is for everyone who likes to add warm, natural tones in their house. It is made of braided jute with a plastic, transparent lining inside makes sure that the basket doesn't leak, so this cutie can immediately claim its place on any kind of surface.",
            image: "amy_basket_jute.png",
            typeId: 2,
            stock: 3,
            price: 16.45,
            trending: true,
            slug: "amy-basket-jute",
        },
        {
            name: "Barnie Basket Terra Ø 13 cm",
            description:
                "Give your urban jungle a natural and summery upgrade with Barnie!  However, keep in mind, this is not waterproof, so placing a saucer at the bottom of the basket is a smart move against leakage.",
            image: "barnie_basket_terra.png",
            typeId: 2,
            stock: 7,
            price: 5.95,
            trending: true,
            slug: "barnie-basket-terra",
        },
        {
            name: "Barnie Basket Cream Ø 13 cm",
            description:
                "Give your urban jungle a natural and summery upgrade with Barnie!  However, keep in mind, this is not waterproof, so placing a saucer at the bottom of the basket is a smart move against leakage.",
            typeId: 2,
            stock: 13,
            price: 5.95,
            trending: true,
            slug: "barnie-basket-cream",
        },
        {
            name: "Barnie Basket Black Ø 13 cm",
            description:
                "Give your urban jungle a natural and summery upgrade with Barnie!  However, keep in mind, this is not waterproof, so placing a saucer at the bottom of the basket is a smart move against leakage.",
            image: "barnie_basket_black.png",
            typeId: 2,
            stock: 11,
            price: 5.95,
            trending: true,
            slug: "barnie-basket-black",
        },
        {
            name: "Baby Orange Terracotta Pot Ø 7 cm",
            description:
                "Terracotta is a real classic but can be fragile. The image pictured is indicative, but please note that the pot you receive can contain small imperfections.",
            image: "baby_orange_terracotta_pot.png",
            typeId: 2,
            stock: 8,
            price: 3.95,
            trending: true,
            slug: "baby-orange-terracotta-pot",
        },
        {
            name: "Orange Terracotta Pot Ø 20 cm",
            description:
                "Terracotta is a real classic but can be fragile. The image pictured is indicative, but please note that the pot you receive can contain small imperfections.",
            image: "orange_terracotta_pot_large.png",
            typeId: 2,
            stock: 13,
            price: 10.95,
            trending: true,
            slug: "orange-terracotta-pot",
        },
        {
            name: "Orange Terracotta Pot Ø 14 cm",
            description:
                "Terracotta is a real classic but can be fragile. The image pictured is indicative, but please note that the pot you receive can contain small imperfections.",
            image: "orange_terracotta_pot_medium.png",
            typeId: 2,
            stock: 13,
            price: 7.95,
            trending: true,
            slug: "orange-terracotta-pot-medium",
        },
        {
            name: "Grey Terracotta Pot Ø 14 cm",
            description:
                "Terracotta is a real classic but can be fragile. The image pictured is indicative, but please note that the pot you receive can contain small imperfections.",
            image: "grey_terracotta_pot_medium.png",
            typeId: 2,
            stock: 5,
            price: 9.95,
            trending: true,
            slug: "gery-terracotta-pot-medium",
        },
        {
            name: "Grey Terracotta Pot Ø 20 cm",
            description:
                "Terracotta is a real classic but can be fragile. The image pictured is indicative, but please note that the pot you receive can contain small imperfections.",
            image: "grey_terracotta_pot_large.png",
            typeId: 2,
            stock: 11,
            price: 10.95,
            trending: true,
            slug: "grey-terracotta-pot-large",
        },
        {
            name: "Atomizer Gold",
            description:
                "Many plants need high humidity because they are naturally used to it. This golden atomizer is not only handy, but also has a nice look that makes it a fun decorative item!",
            image: "atomizer_gold.png",
            typeId: 3,
            stock: 11,
            price: 28.95,
            trending: true,
            slug: "atomizer-gold",
        },
        {
            name: "Terracotta Rain Watering Can",
            description:
                "This handmade terracotta thumb watering can consists of a hole at the top and small holes at the bottom that provides your plants with a lovely rain shower.",
            image: "terracotta_watering_can.png",
            typeId: 3,
            stock: 5,
            price: 12.45,
            trending: true,
            slug: "terracotta-watering-can",
        },
        {
            name: "Elho Manny Watering Set",
            description:
                "Manny is our basic water giver made from 100% recycled plastic and is also fully recyclable after use. Despite the fact that you won't get to this anytime soon because of Manny's timeless look and operation, we think this is a huge plus.",
            image: "elho_manny_watering_set.png",
            typeId: 3,
            stock: 14,
            price: 20.45,
            trending: true,
            slug: "elho-manny-watering-set",
        },
        {
            name: "Ancho Watering Can Black",
            description:
                "The Watering can is pretty in every interior as is it completely made of metal. Next to its beauty, the can has a cylinder shape with a capacity of approximately 1.2L.",
            image: "ancho_watering_can_black.png",
            typeId: 3,
            stock: 9,
            price: 20.95,
            trending: true,
            slug: "ancho-watering-can-black",
        },
        {
            name: "Ancho Watering Can Green",
            description:
                "The Watering can is pretty in every interior as is it completely made of metal. Next to its beauty, the can has a cylinder shape with a capacity of approximately 1.2L.",
            image: "ancho_watering_can_green.png",
            typeId: 3,
            stock: 13,
            price: 20.95,
            trending: true,
            slug: "ancho-watering-can-green",
        },
        {
            name: "Haws Watering Can Copper",
            description:
                "With the Haws Watering Can (1L) you will never forget to water your beauty's again. It is easy to store or also to use as decoration.",
            image: "haw_watering_can_copper.png",
            typeId: 3,
            stock: 9,
            price: 100.45,
            trending: true,
            slug: "haw-watering-can-copper",
        },
        {
            name: "Elho Plunge Watering Can Black",
            description:
                "Because of its unique, stylish appearance, it is also a nice decoration piece. The black plastic watering can (1.7L) has a slim neck and a big filling opening, which makes it comfortable to hold.",
            image: "elho_plunge_watering_can_black.png",
            typeId: 3,
            stock: 10,
            price: 14.45,
            trending: true,
            slug: "elho-plunge-watering-can-black",
        },
        {
            name: "Potting Soil",
            description:
                "Give your plants a boost with our potting soil! This universal soil mixture is the ideal breeding ground that helps your plants grow. It can be used for all types of indoor plants.",
            image: "potting_soil.png",
            typeId: 3,
            stock: 5,
            price: 6.45,
            trending: true,
            slug: "potting-soil",
        },
        {
            name: "Cutting Soil",
            description:
                "Our cutting soil is perfect for your cuttings to form roots and eventually grow into duplicates of your mother plant. It has a fine, compact and regular structure, which ensures even water and food supply and therefore prevents dehydration.",
            image: "cutting_soil.png",
            typeId: 3,
            stock: 20,
            price: 3.95,
            trending: true,
            slug: "cutting-soil",
        },
        {
            name: "Sphagnum Moss",
            description:
                "Sphagnum Moss improves the structure of potting soil. It can hold up to 20 times its own weight of water! This keeps the potting soil always moist, which is especially appreciated by many tropical plants. The bags are around ~450 grams.",
            image: "sphagnum_moss.png",
            typeId: 3,
            stock: 25,
            price: 5.95,
            trending: true,
            slug: "sphagnum-moss",
        },
        {
            name: "Hydro Grains",
            description:
                "The grains absorb moisture, not only from the soil but also from the roots! You can put them on the bottom or on top, so excess water is evenly distributed throughout it. The solution for pots without any drainage holes.",
            image: "hydro_grains.png",
            typeId: 3,
            stock: 26,
            price: 4.95,
            trending: true,
            slug: "hydro-grains",
        },
        {
            name: "French Bark",
            description:
                "The bark creates a chunky structure within the soil, facilitating the efficient drainage of excess water while maintaining a loose texture that promotes root development.",
            image: "french_bark.png",
            typeId: 3,
            stock: 15,
            price: 9.45,
            trending: true,
            slug: "french-bark",
        },
        {
            name: "Living Cushion Moss",
            description:
                "When you're into the swing of creating your terrarium, these fun pillow mosses are an absolute must!This cushion moss has different shades of green to make it look as real as possible.",
            image: "living_cushion_moss.png",
            typeId: 3,
            stock: 25,
            price: 5.45,
            trending: true,
            slug: "living-cushion-moss",
        },
        {
            name: "Lava Rocks",
            description:
                "Experience great aeration and drainage, promoting robust root development while preventing root rot. Our rocks also provide natural insulation, maintaining a cosy temperature around the roots.",
            image: "lava_rocks.png",
            typeId: 3,
            stock: 23,
            price: 4.95,
            trending: true,
            slug: "lava-rocks",
        },
        {
            name: "Perlite",
            description:
                "Thanks to its airy and lightweight nature, roots easily navigate through the substrate. With a neutral pH, it provides a stable environment for newly developing roots.",
            image: "perlite.png",
            typeId: 3,
            stock: 13,
            price: 6.45,
            trending: true,
            slug: "perlite",
        },
        {
            name: "Active Charcoal",
            description:
                "Adding a layer of active charcoal to the bottom, underneath the soil, will help to protect the plant from overwatering. It even absorbs toxics to protect the soil and roots from bacteria's and fungal.",
            image: "active_charcoal.png",
            typeId: 3,
            stock: 3,
            price: 9.45,
            trending: true,
            slug: "active-charcoal",
        },
        {
            name: "Living Moss",
            description:
                "It's a big fan of moist environments and therefore a perfect base for a terrarium. Living moss is also great for other creative purposes, for example making your own kokedama ball.",
            image: "living_moss.png",
            typeId: 3,
            stock: 14,
            price: 4.95,
            trending: true,
            slug: "living-moss",
        },
        {
            name: "Vermiculite",
            description:
                "A lightweight substrate that stimulates plant growth! With its great aeration and drainage properties, vermiculite boosts the development of robust and healthy roots.",
            image: "vermiculite.png",
            typeId: 3,
            stock: 33,
            price: 4.95,
            trending: true,
            slug: "vermiculite",
        },
        {
            name: "Coco Fibre",
            description:
                "With great aeration and moisture retention, coco fiber creates an optimal environment where roots thrive in plenty of oxygen without drying out quickly.",
            image: "coco_fibre.png",
            typeId: 3,
            stock: 23,
            price: 5.95,
            trending: true,
            slug: "coco-fibre",
        },
        {
            name: "Peat Chunks",
            description:
                "Peat is a wet, oxygen-deficient soil type with a sponge-like structure consisting of plant material. It stores nutrients more easily, therefore ensuring a good root development and a beautiful growing plant. In fact, all plants will be happy with this addition!",
            image: "peat_chunks.png",
            typeId: 3,
            stock: 35,
            price: 3.95,
            trending: true,
            slug: "peat-chunks",
        },
        {
            name: "Neem Oil",
            description:
                "This is a natural remedy that fight pests on your green friends. It is effective against moulds, spider mites, thrips, mealy bugs and many other insects and can even be used preventively!",
            image: "neem_oil.png",
            typeId: 3,
            stock: 14,
            price: 13.45,
            trending: true,
            slug: "neem-oil",
        },
        {
            name: "Mourning Fly Catcher Yellow",
            description:
                "The Fungus Gnats Catcher ensures that these insects won't be able to lay eggs in the soil of your plant anymore. It contains 10 fly traps, that are made of recycled plastic and have to be placed in the soil of your effected plant.",
            image: "mourning_fly_catcher_yellow.png",
            typeId: 3,
            stock: 13,
            price: 7.95,
            trending: true,
            slug: "mourning-fly-catcher-yellow",
        },
        {
            name: "Plant Soap",
            description:
                "It can be used to pre-treat mealybugs, thrips, aphids, whiteflies, scale insects, soft scales and spider mites. Clean your plants with this remedy and then let them dry thoroughly.",
            image: "plant_soap.png",
            typeId: 3,
            stock: 33,
            price: 10.45,
            trending: true,
            slug: "plant-soap",
        },
        {
            name: "Biological pest control: White Fly",
            description:
                "With each order, you'll receive 5 cards containing a total of 300 Mosi. Simply hang these cards near the affected plants, and let the creatures take care of the rest.",
            image: "pest_control_white_fly.png",
            typeId: 3,
            stock: 23,
            price: 14.95,
            trending: true,
            slug: "biological-pest-control-white-fly",
        },
        {
            name: "Biological pest control: aphids",
            description:
                "Meet Puncta, also known as ladybug larvae, natural predators of aphids. These creatures can consume between 200-300 aphids over their lifespan. After 4-6 weeks, puncta larvae can mature into ladybugs..",
            image: "pest_control_aphids.png",
            typeId: 3,
            stock: 15,
            price: 30.95,
            trending: true,
            slug: "biological-pest-control-aphids",
        },
        {
            name: "Pest control: spider mites",
            description:
                "Each of these creatures can consume up to 160 spider mite eggs, and a package typically contains around 100 of them.",
            image: "pest_control_spider_mites.png",
            typeId: 3,
            stock: 23,
            price: 12.45,
            trending: true,
            slug: "pest-control-spider-mites",
        },
        {
            name: "Biological pest control: spider mites",
            description:
                "They work invisibly and extremely fast and search your plants for spider mites. A predatory mite can eat up to 5 adult spider mites or 20 young spider mites (eggs) per day.",
            image: "bio_pest_control_spider_mites.png",
            typeId: 3,
            stock: 33,
            price: 20.45,
            trending: true,
            slug: "bio-pest-control-spider-mites",
        },
        {
            name: "Biological pest control: fungus gnats",
            description:
                "They are living soil organisms, as they occur in nature and help nature. So when you use these rescuers, you are using the natural way, which is a nice idea!",
            image: "pest_control_phungus_gnats.png",
            typeId: 3,
            stock: 25,
            price: 15.95,
            trending: true,
            slug: "pest-control-phungus-gnats",
        },
        {
            name: "Sticky Leaf Mourning Fly Catcher Green",
            description:
                "Sticky Leafs come to the rescue! The pack contains 5 sticky leaves, which are made of paper and should be placed in the soil of the affected plant.",
            image: "mourning_fly_catcher_green.png",
            typeId: 3,
            stock: 26,
            price: 7.45,
            trending: true,
            slug: "mourning-fly-catcher-green",
        },
        {
            name: "Nutrition",
            description:
                "It's easy to use, non-toxic and jam-packed with goodness. Love your plants, love your planet! Plus it's super concentrated, meaning that just a tiny bottle will go a long, long way.",
            image: "nutrition.png",
            typeId: 3,
            stock: 23,
            price: 6.95,
            trending: true,
            slug: "nutrition",
        },
        {
            name: "Edward Pruning Shears Silver",
            description:
                "Edward is razor-sharp, super small, about 11 cm and therefor easy to use! Make sure that you always disinfect the blades of the scissors before use.",
            image: "edward_pruning_shears_silver.png",
            typeId: 4,
            stock: 23,
            price: 7.95,
            trending: true,
            slug: "edward-pruning-shears-silver",
        },
        {
            name: "Potting scoop",
            description:
                "This potting scoop is perfect to help you to take care of your plants! You will have a good grip on the scoop, since it has an ergonomic handle.",
            image: "potting_scoop.png",
            typeId: 4,
            stock: 3,
            price: 4.95,
            trending: true,
            slug: "potting-scoop",
        },
        {
            name: "Monstera Propagation Station",
            description:
                "The propagation station is shaped like a beautiful varigated monstera leaf and is made of high-quality plaster composite.",
            image: "monstera_propagation_station.png",
            typeId: 4,
            stock: 17,
            price: 25.95,
            trending: true,
            slug: "monstera-propagation-station",
        },
        {
            name: "Biodegradable Seedling Pots",
            description:
                "Want to grow a tiny seed or baby cutting into a beautiful adult plant? Then these pots are a must-have. The seedling pots are 100% organic and biodegradable, and they even make the soil more fertile as they break down into humus.",
            image: "biodegradbla_seeding_pots.png",
            typeId: 4,
            stock: 23,
            price: 3.45,
            trending: true,
            slug: "biodegradbla-seeding-pots",
        },
        {
            name: "Seedling Pots Tray",
            description:
                "This Seedling Pots on Tray allows you to grow cuttings and seeds, without taking up a lot of space. Besides being super easy to use, these trays are made from sustainable and biodegradable material.",
            image: "seedling_pots_tray.png",
            typeId: 4,
            stock: 13,
            price: 3.95,
            trending: true,
            slug: "seedling-pots-tray",
        },
        {
            name: "Propagation Erlenmeyer Flask",
            description:
                "Thanks to the narrow mouth of the Propagation Erlenmeyer flask, your little cutting stays dry and the roots have all the room they need to grow in the wide space.",
            image: "propagation_erlebneyer_flask.png",
            typeId: 4,
            stock: 33,
            price: 9.95,
            trending: true,
            slug: "propagation-erlebneyer-flask",
        },
        {
            name: "Susan Pruning Scissors",
            description:
                "Her narrow scissors make it easy to get behind all the small branches and cut everything off in a second. This way, it works quickly but most importantly, accurately.",
            image: "susan_pruning_scissors.png",
            typeId: 4,
            stock: 21,
            price: 7.45,
            trending: true,
            slug: "susan-pruning-scissors",
        },
        {
            name: "Potting Mat",
            description:
                "With this foldable potting mat you can repot, loosening, propagate and prune your plants without getting your counter, table or floor dirty. The potting mat is 100% waterproof and super easy to roll up.",
            image: "potting_mat.png",
            typeId: 4,
            stock: 13,
            price: 19.95,
            trending: true,
            slug: "potting-mat",
        },
        {
            name: "Measuring Cup",
            description:
                "This plastic measuring cup, which goes up to 100ml, is ideal for measuring the right quantities.",
            image: "measuring_cup.png",
            typeId: 4,
            stock: 23,
            price: 6.45,
            trending: true,
            slug: "measuring-cup",
        },
        {
            name: "Toby Terrarium Pickup Tool",
            description:
                "This is an extra-long pickup tool which is extendable to about 70cm! He is specially made for terrarium work and therefore made of stainless steel material.",
            image: "toby_terrarium_pickup_tool.png",
            typeId: 4,
            stock: 4,
            price: 8.45,
            trending: true,
            slug: "toby-terrarium-pickup-tool",
        },
        {
            name: "Toby Terrarium Tool Kit",
            description:
                "This is a two-piece terrarium tool kit that includes an extendable rake and shovel. The tool kit is specially made for terrarium work and therefore made of stainless steel material.",
            typeId: 4,
            stock: 9,
            price: 14.45,
            trending: true,
            slug: "toby-terrarium-tool-kit",
        },
        {
            name: "Toby Terrarium shears",
            description:
                "Extra-long pair of scissors of about 25cm with curved blades. He is specially made for terrarium work and therefore made of stainless steel material.",
            image: "toby_terrarium_shears.png",
            typeId: 4,
            stock: 13,
            price: 10.45,
            trending: true,
            slug: "toby-terrarium-shears",
        },
        {
            name: "Toby Terrarium tweezers",
            description:
                "Extra-long tweezer of approximately 25cm. He is specially made for terrarium work and therefore made of stainless steel material.",
            image: "toby_terrarium_tweezers.png",
            typeId: 4,
            stock: 16,
            price: 5.95,
            trending: true,
            slug: "toby-terrarium-tweezers",
        },
        {
            name: "Jules Propagation Set",
            description:
                "Are you looking for a tool that will allow you to have all your cuttings on display? Then our Jules propagation station is the one for you! It has a wooden base, where 5 clear glass tubes are placed in.",
            image: "jules_propagation_set.png",
            typeId: 4,
            stock: 26,
            price: 16.45,
            trending: true,
            slug: "jules-propagation-set",
        },
        {
            name: "Manuela Hanging Vase",
            description:
                "You can use our propagation stations for this, you can choose to propagate several cuttings at the same time or you can choose one favorite plant. ",
            image: "manuela_hanging_vase.png",
            typeId: 4,
            stock: 23,
            price: 7.95,
            trending: true,
            slug: "manuela-hanging-vase",
        },
        {
            name: "Henry Grow Light Bulbs",
            description:
                "Don't be shocked by his bright and pink light, whith his 756 lumens he provides your plant with just the right amount of light to make them grow! With their E27 fitting and an A21 shape they will fit perfectly in most lamp stands! ",
            image: "henry_grow_light_bulbs.png",
            typeId: 4,
            stock: 26,
            price: 43.95,
            trending: true,
            slug: "henry-grow-light-bulbs",
        },
        {
            name: "Greenhouse Cabinet Grow Light LED 20W",
            description:
                "Dreaming of an indoor jungle that exceeds all expectations? This set of 4 LED grow lights from Secret Jardin is your secret weapon! Each strip, glowing with warm white light, is a powerful 20 watts at 24 volts and stretches over 50 cm.",
            image: "cabinet_grow_light_led.png",
            typeId: 4,
            stock: 23,
            price: 144.95,
            trending: true,
            slug: "cabinet-grow-light-led",
        },
        {
            name: "Elho Leah Grow Light",
            description:
                "Leah the adjustable Grow Light is great for these colder and darker days. You can easily place her in the soil of your plant and the best about Leah is that the stick is extendable from 36 cm up to 100 cm!",
            image: "elho_leah_grow_light.png",
            typeId: 4,
            stock: 33,
            price: 62.95,
            trending: true,
            slug: "elho-leah-grow-light",
        },
        {
            name: "Elho Coen Light Garden Green",
            description:
                "With the light garden you can easily grow your own plants and cuttings all year round. This clever system uses a special coloured lamp to optimise the growth of your plants.",
            image: "elho_coen_light_garden_green.png",
            typeId: 4,
            stock: 15,
            price: 130.45,
            trending: true,
            slug: "elho-coen-light-garden-green",
        },
        {
            name: "Grow Light Rings",
            description:
                "With its three rings, it is perfect for placing in a cosy group of plants. You do this by attaching the rings to a transparent stick; when the lamp is seated properly, you can also adjust the ring's height.",
            image: "grow_light_rings.png",
            typeId: 4,
            stock: 11,
            price: 31.45,
            trending: true,
            slug: "grow-light-rings",
        },
        {
            name: "Olly Terrarium Large",
            description:
                "This product consists of only the terrarium jar. Diameter: 29 cm. Height: 38 cm",
            image: "olly_terrarium_large.png",
            typeId: 4,
            stock: 3,
            price: 9.45,
            trending: true,
            slug: "olly-terrarium-large",
        },
        {
            name: "Bello Terrarium Medium",
            description:
                "The Bello terrarium is 32 centimeters high and has a diameter of 21 centimeters. Create your own unique terrarium with Bello.",
            image: "bello_terrarium_medium.png",
            typeId: 4,
            stock: 6,
            price: 18.45,
            trending: true,
            slug: "bello-terrarium-medium",
        },
        {
            name: "Emily Terrarium Mini",
            description:
                "This terrarium will be the perfect environment for your growing baby, it will have increased humidity and temperature to make your plant nice and comfortable.",
            image: "emily_terrarium_mini.png",
            typeId: 4,
            stock: 3,
            price: 13.95,
            trending: true,
            slug: "emily-terrarium-mini",
        },
        {
            name: "Tissue Culture Set",
            description:
                "Would you like to get started with tissue culture? This set contains all the tools needed to grow your mini plant into a beautiful large plant! This set contains a mini terrarium, cutting soil and a small pair of tweezers.",
            image: "tissue_culture_set.png",
            typeId: 4,
            stock: 8,
            price: 16.45,
            trending: true,
            slug: "tissue-culture-set",
        },
        {
            name: "Bello Terrarium Medium Starter Kit",
            description:
                "This starter kit includes: Bello Terrarium Medium, Bag of Hydro Grains, Liter Potting Soil, Bag of living cushion moss, Bag of active charcoal, Fittonia Verschaffeltii, Asparagus Fern ,Calathea Lancifolia Insigne",
            image: "bello_terrarium_medium_starter_kit.png",
            typeId: 4,
            stock: 5,
            price: 9.45,
            trending: true,
            slug: "bello-terrarium-medium-starter-kit",
        },
        {
            name: "Monstera Deliciosa Seed Kit",
            description:
                "This kit will equip you with seeds, cutting soil, a name tag, and a kokedama pot. The only thing left to do is provide your seeds with lots of tender love and care.",
            image: "montera_deliciosa_seed_kit.png",
            typeId: 4,
            stock: 6,
            price: 13.45,
            trending: true,
            slug: "montera-deliciosa-seed-kit",
        },
        {
            name: "Succulents Potting Mix Kit",
            description:
                "These substrates are carefully selected. Good to know is that we already have a good basic potting soil mix and based on that we have chosen the additives.",
            image: "succulents_potting_mix_kit.png",
            typeId: 4,
            stock: 25,
            price: 7.95,
            trending: true,
            slug: "succulents-potting-mix-kit",
        },
        {
            name: "Clippy Wall Mounting Kit",
            description:
                "In this kit you'll find 5 ‘Clippy's. Screw these onto your wall and simply slide your terracotta pot into. To ensure that the water doesn't leak, there are also 5 corks that fit into the drainage hole.",
            image: "clippy_wall_mounting_kit.png",
            typeId: 4,
            stock: 13,
            price: 19.45,
            trending: true,
            slug: "clippy-wall-mounting-kit",
        },
        {
            name: "Plant Care Tool Set",
            description:
                "If you need to remove old stems or are going to repot your plant, this 2-piece set is an absolute must. It includes a metal garden shovel and pruning shears.",
            typeId: 4,
            stock: 13,
            price: 32.45,
            trending: true,
            slug: "plant-care-tool-set",
        },
        {
            name: "Soil Checker",
            description:
                "A soil checker that does its job without fuss - that's what you want! You just stick it into the ground to take a small soil sample at different depths.",
            image: "soil_checker.png",
            typeId: 4,
            stock: 23,
            price: 13.95,
            trending: true,
            slug: "soil-checker",
        },
    ],
    types: [{ name: "plants" }, { name: "pots" }, { name: "care" }, { name: "accessories" }],
};

module.exports = dbContents;
